---
title: "Analysis methods for characterizing the climate sensitivity of annual growth and woody productivity using tree-rings"
author: "Kristina Anderson-Teixeira, Valentine Herrmann"
output: 
  pdf_document:
    citation_package: natbib
    fig_caption: yes
bibliography: [library.bib,  packages.bib]
biblio-style: apalike
csl: apa.csl
    
header-includes:  \usepackage{float}
                  \usepackage{caption}
                  \captionsetup[table]{font=footnotesize}
                  \captionsetup[figure]{font=footnotesize}
                  \captionsetup[figure]{labelformat=empty}
                  \captionsetup[table]{labelformat=empty}

---


# Goals / principles
- predict growth based on climate drivers *and* tree size, by species, so that we can subsequently scale to plot level to predict woody stem productivity $ANPP_{stem}$
- allow non-linear fits of growth to climate variables (note that this contrasts with traditional dendro methods)
- consider multiple relevant climate drivers simultaneously

# Overview

There are 3 basic steps:

1. Identify most important climatic drivers of individual growth

2. Identify best multivariate statistical model accounting for climate and DBH

3. Scale to the ecosystem by combining statistical model with census data

These are outlined below ("Current methodology"), with additional considerations and alterative approaches outlined later ("Considerations and alternative approaches")

# Current methodology

## Data inputs

### Raw data:

*needed from collaborators*

1. Cross-dated tree-ring records of radial growth increments (typically, .rwl files)

2. DBH of cored trees (any year). If not available, we can estimate DBH for trees on which the cores hit center.

*helpful to get from collaborators*

3. Bark thickness, preferably bark thickness allometries (particularly important for trees with very thick bark)

*requested if collaboratos believe they have something better than what we're using*

4. Biomass allometries. Note that we've compiling biomass allometries for ForestGEO sites in "[allo-db](https://github.com/forestgeo/allodb)", and have already sought out recommendations of site PIs.  

5. Monthly climate data spanning the length of tree-ring records. We're currently using data from the CRU database, which has ~10 climate variables available, but in some cases it may be better to use alternative data sources.

### Processed data that we put into model:

1. Tree growth - We start with raw data on radial growth increments (i.e., tree-ring widths). Optionally (probably preferably), we convert this to aboveground biomass increments ($\Delta AGB$) prior to analysis. This requires DBH (see below) and a biomass allometry.

2. Tree diameters -  This requires reconstruction of the historical DBH. We need DBH for any year. Ideally, we want to use a bark thickness allometry to correct for changing bark thickness.

3. Monthly climate data. We're currently using the ~10 climate variables available through CRU, but could consider others.


## Step 1. Identify most important climatic drivers

1. Detrend individual tree growth records (radial growth increments or $\Delta AGB$) by fitting a spline using a GAM, thereby producing residuals. Rather than averaging by species as per traditional dendro methods, we will analyze individual-level residuals.

2. Use the [climwin](https://cran.r-project.org/web/packages/climwin/index.html) R package, described in [this paper](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12590), to identify the time window over which each candidate climate variable most strongly influences tree growth. Specifically, we put the put residuals in *climwin* with with mixed effects model: `residual ~ [climate] + species+ treeID (random effect)`. Outputs are saved [here](https://github.com/EcoClimLab/ForestGEO-climate-sensitivity/blob/master/results/ALL_species_mixed_model_on_residuals/). Example output is shown in Fig. 1.

![**Fig. 1. Example output from Climwin**. This example, from SCBI, looks at the influence of precipitation on radial growth increments. It identifies June-July of the current growing season as the most important window for precipitation's influence on annual growth. Detailed explanation can be found in the climwin publication (referenced above).](figures/ALL_species_mixed_model_on_core_measurement_residuals_pre_absolute_mean_quad_-1374.75_2_1.png)

3. For each candidate climate variable, we move forward with that variable over the time window identified by climwin as a candidate climate variable for the multivariate models.

## Step 2. Identify best multivariate statistical model accounting for climate and DBH

1. Check colinearity among candidate climate variables; remove those that are redundant

2. For each species, run GAM models including every combination of climate variable, DBH, and splines on year fit to each individual.

3. rank models to determine best

4. sum variable weights to determine which drivers are most important

## Step 3. Scale to the ecosystem by combining statistical model with census data



\newpage
# Considerations and alternative approaches

## Species- versus individual-level analysis

- Species-level chronologies seem to provide the clearest picture of climate sensitivity, using methods optimized by dencrochronologists (e.g., Helcoski et al. 2019). However, they aren't compatible with analysis of the roles of ecological factors, including tree size. 

- Individual-level residual analysis seems to work fine for pulling out the climate signal, and is our current approach.

## Response metric


- **ring width (radial growth)** - Annual ring width from individual-level chronologies. Current intention is to focus on this. Used in [Helcoski et al. 2019](https://nph.onlinelibrary.wiley.com/doi/abs/10.1111/nph.15906).

- **biomass increments** - If we go beyond ring width, biomass increment would be preferable to BAI. I currently think it makes more sense to scale to biomass after statistically predicting ring width increment, but biomass increment could work. **It's worth giving further consideration to the issue of whether to scale to biomass before or after running the statistica model.** 

    - [Foster et al. (2016)](https://github.com/EcoClimLab/ForestGEO-climate-sensitivity/blob/master/methods/references/Foster_et_al-2016-Global_Change_Biology.pdf) used indivdiual-level biomass increments. 
   
     - [Teets et al. 2018](https://onlinelibrary.wiley.com/doi/abs/10.1111/gcb.14120) summed biomass increments from cored trees at the species and stand level. They state, "Summing annual biomass increments maintains the signals from individual trees while homogenizing the effect of tree-level factors such as tree size and crowding." This logic makes sense. However, it requires that sampling be proportional to community composition. 
   
- **percent biomass change** - potential option that would be less strongly dependent on size than biomass increments

- **basal area increment (BAI)** - BAI is commonly considered (by dendrochronologists) to be independent of DBH (or at least moresy than ring width) after trees pass a juvenile growth phase, the logic being that if a tree produces a constant amount of stem wood area each year, BAI will hold steady and ring width will decline. However, while this may hold true in some cases such as very old conifers, in most closed-canopy forests around the world, radial/ diameter growth *increases* with DBH (e.g., Muller-Landau et al. 2006, [Anderson-Teixeira et al. 2015](https://www.researchgate.net/publication/277918165_Size-related_scaling_of_tree_form_and_function_in_a_mixed-age_forest)). There are some likely differences between trees represented by tree-rings (survivors) and the community as a whole, but in [Helcoski et al. 2019](https://nph.onlinelibrary.wiley.com/doi/abs/10.1111/nph.15906) we show a positive relationship of radial growth to DBH from tree-rings. The implication--based on basic geometry--is that BAI increases even more strongly with DBH than does radial growth, and hence BAI should *not* be considered independent of DBH. Furthermore, BAI in itself is not very meaningful, as wood is added in three dimensions, and BAI only accounts for two. Thus, KAT sees no *a priori* motivation to use BAI over ring width. BAI was used by and Alexander et al. (in review) but without assumption that BAI is independent of DBH. 


## Identifying the most important climatic drivers

[Helcoski et al. 2019](https://nph.onlinelibrary.wiley.com/doi/abs/10.1111/nph.15906), [GitHub repo with full results](https://github.com/SCBI-ForestGEO/climate_sensitivity_cores) analyzed climate sensitivity using traditional dendro methods and gave a reliable (as far as we know!) picture of climate sensitivity at SCBI. From our explorations of other analysis methods on the same data, it seems that pulling out a reliable climate signal *requires* indivdidual-level detrending of cores. Our attempt to do this with raw growth data, using climwin and a mixed effects model to account for DBH and year, resulted in weak or absent climate correlations that didn't align with Helcoski results. However, if we fit splines to individual core sequences and then analyze these data in *climwin*, we get results that are generally very consistent with Helcoski (except that they don't pull out an opposite signal from the previous growing season).

We have two completementary ways of looking at climate sensitivity:

1. The [climwin](https://cran.r-project.org/web/packages/climwin/index.html) R package, described in [this paper](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12590), is currently our best known option for identifying the most important climate drivers. This works with species-level chronologies or individual-level analysis, and can integrate with most types of regression models that can be implemented in R. We have it working with *lmer* (see [issue #1](https://github.com/EcoClimLab/ForestGEO-climate-sensitivity/issues/1)).

2. The "quilt plots" in [Helcoski et al. 2019](https://nph.onlinelibrary.wiley.com/doi/abs/10.1111/nph.15906) work well for visualizing the big-picture of multiple variables/ months / species, and are a useful complement to *climwin*. So far, we have only done this for species-level residual chronologies, not with individual-level analyses. However, there is no reason (other than potentially complex coding) why we couldn't make similar "quilt plots" for individual-level analyses.

### Potential alternatives
#### Mixed-effects model in climwin on raw data (not optimal)
This approach did not work well for pulling out climate signals.

- Used *climwin* with with mixed effects model: `diameter.growth ~ [climate] + DBH + year + treeID (random effect)`

- Some of the results aligned with [Helcoski et al. 2019](https://nph.onlinelibrary.wiley.com/doi/abs/10.1111/nph.15906), but many don't (e.g., positive effect of DTR, where Helcoski found negative).

- Some potential clean-up that may make results more clear: remove outliers, ln-transform age and growth?, remove DTR as predictor variable. 

- However, individual-level detrending seems to be the way to go for identifying the most important climate drivers.



## Accounting for DBH (and other factors)
- DBH must be accounted for in the model. [Peters et al. (2015)](https://onlinelibrary.wiley.com/doi/epdf/10.1111/gcb.12826) reviews some methods

- Should we account for age too?




## Scaling to ecosystem level
### What others have done:

- [Helcoski et al. 2019](https://nph.onlinelibrary.wiley.com/doi/abs/10.1111/nph.15906) used tree-rings to charactize growth as a function of DBH, and assumed that the proportional response to climate was consistent across size classes. We want to move beyond that.
- [Teets et al. 2018](https://onlinelibrary.wiley.com/doi/abs/10.1111/gcb.14120) used stratefied random sample based on community composition. They summed across individuals to get values proportional to ecosystem-level productivity. This approach does not work when sampling is not carefully stratefied relative to community composition.


\newpage
## Other statistical models of individual-level tree-ring data:
- [Foster et al. (2016)](https://github.com/EcoClimLab/ForestGEO-climate-sensitivity/blob/master/methods/references/Foster_et_al-2016-Global_Change_Biology.pdf) used an individual level Baysian heriarchical model to characterize to what extent whole-tree growth depends on climatic, tree, and stand structural variables.

- M. Ross Alexander and colleagues (in review-TREAT CONFIDENTIALLY) "used generalized additive models (GAMs) using the gam function in the mgcv R package to allow for non-linear climate and size effects without prescribing a priori functional forms (Polansky & Robbins 2013; Peters et al.2015, Simpson 2018, Wood 2003).  ....Year effects were estimated using a 4-knot thin plate regression spline fit by sampling plot to capture stand dynamics such as suppression or release events that may have influenced growth through time. Size effects were estimated for each species using 3-knot thin-plate regression splines fit to reconstructed DBH (Wood 2003)."

    Peters, R.L., Groenendijk, P., Vlam, M. & Zuidema, P.A. (2015). [Detecting long‐term growth trends using tree rings: a critical evaluation of methods](https://onlinelibrary.wiley.com/doi/abs/10.1111/gcb.12826). Glob Change Biol, 21, 2040–2054.

    Polansky, L. & Robbins, M.M. (2013). Generalized additive mixed models for disentangling long‐term trends, local anomalies, and seasonality in fruit tree phenology. Ecology and Evolution, 3, 3141–3151.

    Simpson, G.L. (2018). [Modelling palaeoecological time series using generalised additive models](https://www.frontiersin.org/articles/10.3389/fevo.2018.00149/full). Frontiers in Ecology and the Environment, 6, 1–21.

    Wood, S.N. (2003). Thin plate regression splines. Journal of the Royal Statistical Society: Series B (Statistical Methodology), 65, 95–114.

