---
title: " "

output: 
  pdf_document:
    fig_caption: yes
    
header-includes:  \usepackage{float}
                  \usepackage{caption}
                  \captionsetup[table]{font=footnotesize}
                  \captionsetup[figure]{font=footnotesize}
                  \captionsetup[figure]{labelformat=empty}
                  \captionsetup[table]{labelformat=empty}
---

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
options(knitr.table.format = "latex")
```

\newpage

```{r eval = TRUE, echo=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
sites <- read.csv("sites.csv", stringsAsFactors = FALSE, check.names = FALSE)
sites_table <- subset(sites, select = -c(MAT) ) #drop MAT column
kable(sites_table, format = "latex", booktabs = TRUE,  escape = F)%>%
  column_spec(1, width = "1cm") %>%
  column_spec(2, width = "3cm") %>%
  column_spec(3, width = "3cm") %>%
  #column_spec(6, width = ".5cm") %>%
  column_spec(7, width = "1.4cm") %>%
  column_spec(8, width = "1cm") %>%
  #column_spec(9, width = "2cm") %>%
  column_spec(10, width = "3cm") %>%
  kable_styling(latex_options = c("scale_down", "hold_position"), protect_latex = T) 
```
*don't trust this climate data