---
title: " "

output: 
  pdf_document:
    fig_caption: yes
    
header-includes:  \usepackage{float}
                  \usepackage{caption}
                  \captionsetup[table]{font=footnotesize}
                  \captionsetup[figure]{font=footnotesize}
                  \captionsetup[figure]{labelformat=empty}
                  \captionsetup[table]{labelformat=empty}
---

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
options(knitr.table.format = "latex")
```



```{r eval = TRUE, echo=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
hypotheses <- read.csv("hypothesis_table.csv", stringsAsFactors = FALSE, check.names = FALSE)
hypotheses_table <- subset(hypotheses, table_row > 0, select=c(hypothesis, supported)) # subset to include only records flagged with include ==1, keeping columns to plot
rownames(hypotheses_table) <- c() # removes row names (original row numbers) on hypothesis table
colnames(hypotheses_table) = c("hypotheses and specific predictions","frequency observed")

kable(hypotheses_table, format = "latex", booktabs = TRUE,  escape = F)%>%
  
  column_spec(1, width = "12cm") %>%
  column_spec(2, width = "5cm") %>%

  #pack_rows("Annual growth is simultaneously influenced by water, temperature, DBH, and time. ", 1, 5, latex_gap_space = "1em", colnum = 1, hline_before = FALSE) %>%
  pack_rows("How do precipitation (P) and temperature (T) jointly shape tree growth? ", 1,12, latex_gap_space = "1em", italic= TRUE)%>%
  row_spec(c(1,5,10), bold = T) %>%
  add_indent(c(2:4, 6:9,11:12)) %>%
  pack_rows("How does growth rate vary with stem diameter (DBH)?", 13,17,italic= TRUE, latex_gap_space = "1em", hline_before = FALSE)%>%
  row_spec(c(13), bold = T) %>%
  add_indent(c(14:17)) %>%
  pack_rows("How have growth rates changed through time?", 18,21,italic= TRUE, latex_gap_space = "1em", hline_before = FALSE)%>%
  row_spec(c(18), bold = T) %>%
  add_indent(c(19:21)) %>%
  
  kable_styling(latex_options = c( "hold_position"), protect_latex = T, font_size = 7) 

```

\newpage

```{r eval = TRUE, echo=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
sites <- read.csv("sites.csv", stringsAsFactors = FALSE, check.names = FALSE)
sites_table <- subset(sites, select = -c(MAT, JulyTsd, JanTsd, MAPsd) ) #drop MAT column, plus columns with sd
kable(sites_table, format = "latex", booktabs = TRUE,  escape = F)%>%
  add_header_above(c(" ", " "," ", "1950 - 2019 climate" = 3, " " , " "," "," ")) %>%
  column_spec(1, width = "1cm") %>%
  column_spec(2, width = "3cm") %>%
  column_spec(3, width = "3cm") %>%
  column_spec(4:6, width = "1cm") %>%
  #column_spec(6, width = ".5cm") %>%
  column_spec(7, width = "1.4cm") %>%
  column_spec(8, width = "1cm") %>%
  #column_spec(9, width = "2cm") %>%
  column_spec(10, width = "4cm") %>%
  kable_styling(latex_options = c("scale_down", "hold_position"), protect_latex = T) 
```
